apiVersion : apps/v1
kind: Deployment
metadata:
  name: swetasgitaksupdate 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swetasgitaksupdate
  template:
    metadata:
      labels:
        app: swetasgitaksupdate 
    spec:
      containers:
        - name: swetasgitaksupdate 
          image: akservice001registry.azurecr.io/azurekubeserviceapp:57540
          ports:
          - containerPort: 8080
          imagePullSecrets:
          - name: image-pull-secret
