apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swetasgitaksupdate-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: kubernetes-vm.northeurope.cloudapp.azure.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swetasgitaksupdate
                port:
                  number: 80
